Virtual-Coffee/podcast-transcripts

episodes/1_0.srt, episodes/1_4.srt
- Closes #2
- Closes #3 
- Improve podcast season 1 
- Episode 0
- Episode 4
- Improve/edit transcript manually by listening to the episodes of the podcast.
- Keeping 2 lines for each timestamp as originally generated transcriptions.
=> Improve podcast season 1 episode 0 & 4 

episodes/1_6.srt
Closes #6
- Improve podcast season 1 episode 6
- Improve/edit transcript manually by listening to the episodes of the podcast.
- Keeping 2 lines for each timestamp as originally generated transcriptions.
=> Improve transcription season 1 episode 6

episodes/1_7.srt
Closes #8 
- Improve podcast season 1 episode 7
- Improve/edit transcript manually by listening to the episodes of the podcast.
- Keeping 2 lines for each timestamp as originally generated transcriptions.
=> Improve transripction season 1 episode 7

episodes/1_0.srt, episodes/1_4.srt
Closes #12 
- Fix transcript podcast season 1 episode 0 & 4
- Fix/edit transcript manually by listening to the episodes of the podcast.
- Following the transcriptions' guidelines.
=> Fix transcripts season 1 episode 0 & 4

Transcriptions_Guideline.md
#10 
Add a guideline to keep the consistency throughout the Virtual Coffee podcast's transcriptions.
> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)
=> Add transcriptions guideline

episodes/5_7.srt
Closes #19
- Improve transcript Season 5, Episode 8.
- Fix the format.
=> Improve transcript Season 5 Episode 7

Transcriptions-Guidelines.md
- Add note about colons
- A couple small tweaks
=> Add some notes/clarifications to the guidelines

episodes/6_2.srt
Closes #22 
- Improve transcript Season 6 Episode 2.
- Ran `yarn check-srt` to fix the index and format.
=> Improve transcript Season 6 Episode 2

episodes/5_8.srt
- Fix punctuations and typos in transcript Season 5 Episode 8.
- Ran `yarn check-srt` to adjust index and format.
=> Fix transcript Season 5 Episode 8

episodes/6_6.srt
Closes #37
- Improve transcript Season 6 Episode 6 with Julia Seidman.
- Fix timestamps manually.
- Run `yarn check-srt` and fix incorrect timestamp formatting.
=> Improve Transcription Season 6 Episode 6

episodes/6_5.srt
Closes #31 
- Improve transcript Season 6 Episode 5 with Chad Stewart.
- Fix timestamps manually.
- Run `yarn check-srt` and fix incorrect timestamp formatting.
=> Improve Transcription Season 6 Episode 5

episodes/6_4.srt, episodes/6_5.srt
Closes #32 
- Improve transcript Season 6 Episode 4 with Sadie Jay.
- Fix timestamps manually.
- Run `yarn check-srt` and fix incorrect timestamp formatting.
=> Improve Transcription Season 6 Episode 4

episodes/5_6.srt
Closes #35
- Improve transcript Season 5 Episode 6 with Andrew Bush.
- Fix timestamps manually.
- Run `yarn check-srt` and fix incorrect timestamp formatting.
=> Improve Transcription Season 5 Episode 6

episodes/3_9.srt, episodes/4_2.srt
Improved auto generated transcripts for  Season 4 Episode 2 with Todd Libby.
Ran yarn check-srt to fix incorrect timestamp formatting.
Fixed colon error
closes #47
=> update transcript for 4_2

episodes/4_2.srt
- Improve transcript Season 4 Episode 2 with Todd Libby.
=> Improve transcript Season 4 Episode 2

episodes/6_7.srt
Closes #39 
- Improve transcript Season 6 Episode 7 with Ryan Kahn.
=> Improve episode transcription Season 6 Episode 7

episodes/6_8.srt
Closes #86  
- Improve transcript Season 6 Episode 8 with Shelley McHardy.
=> Improve episode transcription Season 6 Episode 8

episodes/3_3.srt
Closes #57 
- Improve transcript Season 3 Episode 3 with Ayu Adiati.
=> Improve episode transcription Season 3 Episode 3

episodes/6_8.srt, episodes/6_9.srt
Closes #88
- Improve transcript Season 6 Episode 9 (finale) with Bekah, Dan and Kirk.
=> Improve episode transcription Season 6 Episode 9 (finale)

episodes/5_4.srt
Closes #43
- Improve transcript Season 5 Episode 4 with Yolanda Haynes.
=> Improve episode transcription Season 5 Episode 4

Transcriptions-Guidelines.md
Closes #101 
In the `transcriptions-guidelines.md`:
- Added a Table of Content to help with navigation inside the docs.
- Grouping the important things of transcribing.
- Updated double dash and em dash rules to follow common rules.
- Updated examples.
- Updated wordings.
- Fixed formats.
=> Update Transciptions Guidelines
